### ISSUE TITLE
Taerobee 1.4.2.0-release <Grand Adventure's End>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Taerobee#136]
# Taerobee 1.4.2.0-release `<Grand Adventure's End>`

* [ ] version name: `<Grand Adventure's End>`
* [X] Archive last release
* [X] Archive local repo
* [ ] Release

## Create/Update to latest

* [X] folder structure
* [X] readme.md
* [X] .version file
* [X] _releasenotes
* [X] .gitattributes
* [X] .gitignore
* [ ] changelog.md

## .github

* [X] .imgbotconfig
* [X] _settings.yml
* [X] _NewRelease

### workflows

* [X] AVC-VersionFileValidator.yml
* [X] greetings.yml
* [X] createIndexesfromMarkdown.yml
* [X] dotnet.yml (CODE only)

## Update automation

* [X] _release.json
* [X] _buildJSON
* [X] _buildRelease
* [X] _createRelease
* [X] _deploy
* [X] _gitClean
* [X] _pullIssues
* [X] _pullReleaseNotes

## Projects

* [X] move release notes.htm
* [X] clean up GH repo
* [X] fork release
* [X] create repo's Release Project
* [X] create Release issue using short list
* [X] create User Project - Adoption/Release
* [ ] Localization
  * [ ] update wiki
* [ ] Update changelog.md
  * [X] update _release.json
  * [X] backup _release.json
* [ ] Github PR
* [ ] Patreon release for subscribers 🅱️
* [ ] Curseforge release for 🅱️
* [ ] SpaceDock release (after beta on 🤬 )
* [ ] update mod spreadsheet
* [X] update shortlist

**Comment by AtomikkuSan** [comment]
Perhaps we should name this the "Taerobee 1.4.2.0 Release: Grand Adventure's End?"

**Comment by zer0Kerbal** [comment]
> Grand Adventure's End

I don't see why not.
