### ISSUE TITLE
1.4.2.0 Social Media

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Taerobee#139]
# 1.4.2.0 Social Media

* [ ] create/update
  * [X] Kerbal Space Program forum
    * [ ] update original post
      * [ ] title
      * [X] content
    * [ ] create release post
  * [ ] CurseForge
  * [ ] Twitter
  * [ ] SpaceDock
  * [ ] Reddit post
  * [ ] Patreon post
  * [ ] promo vid (30 sec)
    * [ ] Youtube
    * [ ] Twitch

**Comment by AtomikkuSan** [comment]
Have you updated the Spacedock post yet?
If not, I'd like to do it! (At SpaceDock, I still go by AtomicTech)
