### ISSUE TITLE
Localization - Japanese(日本語) <ja.cfg> 

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Taerobee#17]
From Localization created by [zer0Kerbal](https://github.com/zer0Kerbal): zer0Kerbal/Localization#9  

Localization - [Japanese(日本語)][JA] <ja.cfg>  

### GameData

- [ ] add ja.cfg  

### Translation

- [ ] [![日本語][JA]][JA] [Japanese(日本語)][JA] <ja.cfg>  

[JA]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Japanese-flag-sm.png "日本語"  

### Update Documentation

- [ ]  mod Readme 🔢 
- [ ]  releaseNotes.md 🧾 

### GitHub Issues

- [ ] assign to zer0Kerbal
- [ ] assign projects (user and repo)
- [ ] assign label: Localization
- [ ] assign label: help-wanted
- [ ] assign milestone: Localization - Japanese(日本語) <ja.cfg>

### Update Social Media

- [ ] CurseForge
- [ ] CKAN
- [ ] Forum
- [ ] GitHub
- [ ] Patreon
- [ ] Reddit
- [ ] SpaceDock

### Wiki

- [ ] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by AtomikkuSan** [comment]
I could, in theory, write a placeholder .cfg file

**Comment by zer0Kerbal** [comment]
> I could, in theory, write a placeholder .cfg file

I will run this mod through Watson after the 1st. 🍜

**Comment by AtomikkuSan** [comment]
I made a placeholder for the time being. I'd really appreciate it if you could find someone to replace this soon 'cause I think it's sort of crappy but it'll do for the time being.

**Comment by zer0Kerbal** [comment]
[ja.txt](https://github.com/zer0Kerbal/Taerobee/files/8568263/ja.txt)
from Watson (very rough)

**Comment by zer0Kerbal** [comment]
here is a stripped version:
[ja.txt](https://github.com/zer0Kerbal/Taerobee/files/8568394/ja.txt)
