### ISSUE TITLE
Waterfall Effects

### ISSUE THREAD

**Issue by JamesErvin-5** [zer0Kerbal/Taerobee#52]
Using Knight of St. John's Library of Waterfall Plumes and Cores, I've made some placeholder plumes for all the engines in this mod.

They'll likely need some tweaking so they're not final by any means!

**Comment by JamesErvin-5** [comment]
It does need Stock Waterfall Effects as well as the original Waterfall to work.

**Comment by zer0Kerbal** [comment]
Thank you! - will add that to the supports but requires on the `readme.md`
