### ISSUE TITLE
Version 1.4.0.0-release - Social Media

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Taerobee#58]
### Version 1.4.0.0-release - Update Social Media
- [x] create/update 
  - [x] FORUMS:
    - [x] update original forum posting
    - [x] update original forum headline
    - [x] create release posting
  - [x] CurseForge
  - [x] SpaceDock
    - [x] release posting with plaintext notes
    - [x] then update release notes with markdown notes
    - [x] verify/update CKAN listing
  - [x] reddit post
  - [ ] Patreon post
  - [ ] promo vid (30 sec)

**Comment by JamesErvin-5** [comment]
I can help w/ SpaceDock!

**Comment by zer0Kerbal** [comment]
> I can help w/ SpaceDock!

Thank you, just a reminder to update the mod information page if need be. :D

**Comment by JamesErvin-5** [comment]
So whenever you get a chance, could you add me to the SpaceDock authors tab so I can edit the listing?
